version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development

    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/dev
      - NODE_ENV=development
      - AUTH_TOKEN_SECRET=secret
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    entrypoint: ["yarn", "dev"]


  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASES=dev,test
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/pg-init:/docker-entrypoint-initdb.d
      # - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=dracula
